apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - name: node-web-app
        image: node-web-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: node-web-app-config
              key: NODE_ENV
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: node-web-app-config
              key: APP_MESSAGE
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: node-web-app-secret
              key: SECRET_KEY
        command: ["npm", "start"] 