version: '3.8'

services:
  web:
    build: .
    container_name: node-web-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start 